
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int RDIV = 10;
  public static final int RMIN = 18;
  public static final int RLINE = 38;
  public static final int RMODA = 15;
  public static final int RMEDIA = 12;
  public static final int RMUL = 9;
  public static final int RLABEL = 48;
  public static final int RMOD = 11;
  public static final int RPRINT = 33;
  public static final int MAYORQUE = 24;
  public static final int IGUAL = 31;
  public static final int RDOUBLE = 19;
  public static final int RCONSOLE = 32;
  public static final int ID = 4;
  public static final int REXEC = 46;
  public static final int EOF = 0;
  public static final int PARIZQ = 28;
  public static final int DECIMAL = 26;
  public static final int REND = 3;
  public static final int RSUM = 8;
  public static final int RARR = 7;
  public static final int error = 1;
  public static final int COMA = 30;
  public static final int RCOLUMN = 34;
  public static final int CADENA = 25;
  public static final int RTITULO = 41;
  public static final int CUATROP = 21;
  public static final int RMAX = 17;
  public static final int RVAR = 5;
  public static final int RCHAR = 6;
  public static final int MENORQUE = 23;
  public static final int RTITULOY = 45;
  public static final int RTITULOX = 44;
  public static final int RVARIANZA = 16;
  public static final int RVALUES = 47;
  public static final int RRES = 14;
  public static final int DOSP = 22;
  public static final int RPIE = 39;
  public static final int REJEY = 43;
  public static final int REJEX = 42;
  public static final int CORC = 35;
  public static final int CORA = 36;
  public static final int PARDER = 29;
  public static final int RMEDIANA = 13;
  public static final int IDARREGLO = 27;
  public static final int RPROGRAM = 2;
  public static final int RBAR = 37;
  public static final int RHISTOGRAM = 40;
  public static final int PYC = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RPROGRAM",
  "REND",
  "ID",
  "RVAR",
  "RCHAR",
  "RARR",
  "RSUM",
  "RMUL",
  "RDIV",
  "RMOD",
  "RMEDIA",
  "RMEDIANA",
  "RRES",
  "RMODA",
  "RVARIANZA",
  "RMAX",
  "RMIN",
  "RDOUBLE",
  "PYC",
  "CUATROP",
  "DOSP",
  "MENORQUE",
  "MAYORQUE",
  "CADENA",
  "DECIMAL",
  "IDARREGLO",
  "PARIZQ",
  "PARDER",
  "COMA",
  "IGUAL",
  "RCONSOLE",
  "RPRINT",
  "RCOLUMN",
  "CORC",
  "CORA",
  "RBAR",
  "RLINE",
  "RPIE",
  "RHISTOGRAM",
  "RTITULO",
  "REJEX",
  "REJEY",
  "RTITULOX",
  "RTITULOY",
  "REXEC",
  "RVALUES",
  "RLABEL"
  };
}

